name: Continuous Integration

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow for pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image to run the job

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python 3.12.0
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.0  # Specify the version of Python to use

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Lint Python code (optional but recommended)
      - name: Lint Python code with flake8
        run: |
          pip install flake8
          flake8 src/ tests/ --max-line-length=79

      # Step 5: Run tests (using pytest for example)
      - name: Run tests
        run: |
          pip install pytest
          pytest tests/ --maxfail=1 --disable-warnings -q

      # Step 6: Run any custom scripts, such as a pre-deployment task (optional)
      - name: Run custom Python scripts (optional)
        run: |
          python src/scraping.py  # Run your scraping script as a sample task

      # Step 7: Upload artifacts (optional, e.g., saving test results or logs)
      - name: Upload test results to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: tests/results/
          
